apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: apptoput
  name: apptoput
spec:
  ports:
  - name: "6000"
    port: 6000
    targetPort: 6000
  selector:
    io.kompose.service: apptoput
status:
  loadBalancer: {}
