apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: exist
  name: exist
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: exist
    spec:
      containers:
      - image: gcr.io/clusterekaitz/existdb:existdb
        name: exist
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {}
      restartPolicy: Always
status: {}
