apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert -o yaml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: appzenbsortzaile
  name: appzenbsortzaile
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: appzenbsortzaile
    spec:
      containers:
      - image: gcr.io/clusterekaitz/komunikaziojarduera:appZenbSortzaile
        name: appzenbsortzaile
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
